services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - mscommand/.env
    ports:
      - "3334:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - beautique-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U beautique"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - beautique-network
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --quiet"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    env_file:
      - mscommand/.env
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - beautique-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mscommand:
    build:
      context: ./mscommand
    container_name: mscommand
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - mscommand/.env
    ports:
      - "8082:8082"
    networks:
      - beautique-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/ms-beautique/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  mssync:
    build:
      context: ./mssync
    container_name: mssync
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mscommand:
        condition: service_healthy
    env_file:
      - mssync/.env
    ports:
      - "8083:8083"
    networks:
      - beautique-network

volumes:
  postgres_data:
  mongo_data:

networks:
  beautique-network:
    driver: bridge